### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tammana-umasankar** [attdona/NAIS#1]
I am facing issue for compilation of the code. please find the steps which I have executed below.
===================================================
Steps:
===================================================
1. Installed the arm tool chain with the below command
    -> sudo apt install gdb-arm-none-eabi
2. Downloaded the code from git and unziped it.
3. Inside the folder 
    -> cd burba
    -> git clone https://github.com/RIOT-OS/RIOT.git
    -> cd apps/hello-world
    -> make
===================================================
**Output**
===================================================
"make" -C /home/tammana/RIOT/NAIS-master/burba/sys/sbapp_cc3200
In file included from /home/tammana/RIOT/NAIS-master/burba/sys/sbapp_cc3200/sbapp_cc3200.c:4:0:
/home/tammana/RIOT/NAIS-master/burba/sys/sbapp_cc3200/sbapp_priv.h:25:22: fatal error: sockloop.h: No such file or directory
 #include "sockloop.h"
                      ^
compilation terminated.
/home/tammana/RIOT/NAIS-master/burba/RIOT/Makefile.base:81: recipe for target '/home/tammana/RIOT/NAIS-master/burba/apps/hello-world/bin/cc3200-launchxl/sbapp_cc3200/sbapp_cc3200.o' failed
make[3]: *** [/home/tammana/RIOT/NAIS-master/burba/apps/hello-world/bin/cc3200-launchxl/sbapp_cc3200/sbapp_cc3200.o] Error 1
/home/tammana/RIOT/NAIS-master/burba/RIOT/Makefile.base:20: recipe for target 'ALL--/home/tammana/RIOT/NAIS-master/burba/sys/sbapp_cc3200' failed
make[2]: *** [ALL--/home/tammana/RIOT/NAIS-master/burba/sys/sbapp_cc3200] Error 2
/home/tammana/RIOT/NAIS-master/burba/RIOT/Makefile.base:20: recipe for target 'ALL--/home/tammana/RIOT/NAIS-master/burba/sys' failed
make[1]: *** [ALL--/home/tammana/RIOT/NAIS-master/burba/sys] Error 2
/home/tammana/RIOT/NAIS-master/burba/RIOT/Makefile.include:301: recipe for target 'all' failed
make: *** [all] Error 2
===================================================

I could not find the file "sockloop.h" in the source code. Please let me know if I need to install any other components on my Ubuntu?
It does not find the definition for "sockloop_run()" function too.

My another observation 
The makefile "NAIS-master/burba/apps/hello-world/Makefile" is included the below line
                                                                              -I$(BURBA)/sys/protobuf-c
but from the git it does not present this folder/file at all in the specified path.

**Comment by attdona** [comment]
Sorry, it was my fault. I' m in the middle of a refactoring and I did a partial commit that broke the build.
In the meanwhile if you want try to go ahead try to checkout the last but one commit.

**Comment by tammana-umasankar** [comment]
Thanks for your response. I have checkout the last but one version (https://github.com/attdona/NAIS/commit/67ea4f6e9dad49a630af07fee1901666b04d2eeb) and executed the commands as per wiki. The make gives the same issue "work/RIOT/NAIS_OLD/burba/sys/sbapp_cc3200/sbapp_priv.h:25:22: fatal error: sockloop.h: No such file or directory  #include "sockloop.h""

The sockloop.h file does not find in this repository at all. Do I need to install any package or am I missing any step?

**Comment by attdona** [comment]
sockloop.h is an api for a event loop around a select, it is a missing piece of my last pushes.
Please go back another commit, or until the problem disappear.
Now I'm in the wild for a few days without a pc, just with email... 
What version of chip is in your hands? I have tested the RIOT port with a first generation cc3200 and with a servicepack version compatible with SDK 1.2.
I dont know if burba works with Sdk 1.3 out of the box...

**Comment by tammana-umasankar** [comment]
Thanks for your response and I have tried the July 6th version (3rd revision from last) (https://github.com/attdona/NAIS/tree/b50a4a7adc0bc1ec0bc5bcf80ace0dd17f78786d) which is successfully compiled and also executed the sample network application on CC3200 board. 

As per my observation in tcp_connect() function some apis are from TI Simple link layer and some of them are RIOT posix socket apis.(connect() api. In fact sl_connect() is also available.)

Is there anyway to find which socket APIs can use directly without simplelink API for CC3200 board?

**Comment by attdona** [comment]
I've mixed sl_* function with posix call that are macros defined in burba/cpu/cc3200/sdk/simplelink/socket.h.
I'll fix that to avoid confusion.

All socket calls are simplelink calls routed to the cc3200 network processor unit.

**Comment by attdona** [comment]
Compilation problem fixed
